### ISSUE TITLE
Add beautiful image for an open-terrarium

### ISSUE THREAD

**Issue by MalloZup** [MalloZup/ceph-open-terrarium#1]
IN sync with the ceph upstream just add a logo for this README.MD repo. Adapt the markdown acccordingly.

Make 2/3 proposal from a good LOGO rappresenting a terrarium and which would be good also good for ceph project.

**Comment by arpitjainds** [comment]
What kind of logo do you have in mind?

**Comment by MalloZup** [comment]
@arpitjainds ciao! :small_airplane: 
I think something with flowers, and reflecting a `terrarium`

**Comment by arpitjainds** [comment]
Sure. I am on it. If I'll find something, I'll show it here.

**Comment by arpitjainds** [comment]
Hey! I designed this Logo. I hope you'll like this.

![rerrarium](https://user-images.githubusercontent.com/25300562/46610271-ddca8400-cb27-11e8-9a2f-c10d5baf132c.jpg)

**Comment by MalloZup** [comment]
@arpitjainds woah! this is really really  beautiful! :heart: :heart_eyes:  
I have only 2 remarks:

1) about `terrarium` name, we might put inside `ceph-open-terrarium` 
2) we need  to think about to make a relation with `ceph` in the design.

Imho i was thinking either we do the `terrarium` phorme looking as an octopus (if it is not difficult :smile: )
Or we might put an octupus part somewhere, something that remind the octopus :smile_cat: 

Looks really nice

**Comment by arpitjainds** [comment]
Thanks. I'll work something out.

**Comment by MalloZup** [comment]
@arpitjainds thank, your logo looks really beautiful i can only dream about what come next .. :heart_eyes:

**Comment by arpitjainds** [comment]
Hi! how does this look?
![rerrarium1](https://user-images.githubusercontent.com/25300562/46613490-060ab080-cb31-11e8-8bb6-55d387852ccf.jpg)

**Comment by MalloZup** [comment]
@arpitjainds i discussed it with some friends, i love the logo. 

:a:wesome!

Feel free to send the LOGO via a PR. 

(would be really cool if you send the SVG and different formats.. ) 
:love_hotel: :cupid:

**Comment by arpitjainds** [comment]
Just raised a pull request. Please Merge.

**Comment by MalloZup** [comment]
@arpitjainds :heart:  thank you !
