### ISSUE TITLE
Fix typos in documentation ! 

### ISSUE THREAD

**Issue by MalloZup** [MalloZup/ceph-open-terrarium#10]
i have some typo in docs feel free to try out!

**Comment by AlminCode** [comment]
By documentation do you mean README? 

I don't think I can find a Documntation page?

**Comment by MalloZup** [comment]
hi @AlminCode and @KushagraMakharia by doc i mean:

README.md
Architecture.md
and contributing.md 

Feel free to take also other issue like travis ci this are really interesting or other issues.

Anyway thanks for your time :cupid: for any question feel free to ask ! 
Have fun ciao!

**Comment by MalloZup** [comment]
if you want to contribute in Design/DOC/DEC or any topic i will be glad to help!

**Comment by MalloZup** [comment]
I think this is done awesome thx
