### ISSUE TITLE
Add gentoo module image

### ISSUE THREAD

**Issue by MalloZup** [MalloZup/ceph-open-terrarium#35]
Image should be openstack qcow format

**Comment by MalloZup** [comment]
@mudler

**Comment by MalloZup** [comment]
@maximenoel  feel free to post the output of `terraform get`. 

this might work gentoo.osuosl.org/experimental/amd64/openstack/gentoo-openstack-amd64-default-latest.qcow2

**Comment by MalloZup** [comment]
for any info feel free to ping

**Comment by maximenoel** [comment]
@MalloZup I had my work on my branch add_gentoo. 
With terraform get I have => 

> - module.cloudinit
> - module.gentoo

and with terraform init I have =>

> Initializing modules...
> - module.cloudinit
> - module.gentoo
> 
> Error: resource 'libvirt_domain.gentoo' config: unknown resource 'libvirt_volume.gentoo_disk' referenced in variable libvirt_volume.gentoo_disk.*.id

I'm not completely understand what QUEM does...

**Comment by MalloZup** [comment]
@maximenoel  ok sound good error, isn\t sexy :smile: ?

The error you have is more a terraform specif one.

`
Error: resource 'libvirt_domain.gentoo' config: unknown resource 'libvirt_volume.gentoo_disk' referenced in variable libvirt_volume.gentoo_disk.*.id
`

This mean something is wrong on the TF logic.

Feel free to create a PR with WIP prefix so i can have a look and show you were is not working.

**Comment by MalloZup** [comment]
https://github.com/sanemat/do-not-merge-wip-for-github
