### ISSUE TITLE
create pillar dinamically

### ISSUE THREAD

**Issue by MalloZup** [MalloZup/ceph-open-terrarium#43]
we need to create the pillar form terraform dinamically adding the ip of master-salt so the minion can get it during salt-states exec.

**Comment by MalloZup** [comment]
fix static ip https://github.com/MalloZup/ceph-open-terrarium/commit/efab99d1466189b7a42abd77682f0f16a3b2571d#diff-38fceca90c265bd5d409459894da753cR1

**Comment by MalloZup** [comment]
@meaksh https://github.com/MalloZup/ceph-open-terrarium/commit/194052ec0341dba6aa0b86af3d9e3da019fda5db

So basically i take the ips from `host.txt` which is generated at moment from terraform, then i run that script which generated `pillar` and `roster`.

How sounds for you this approach? to me looks good but maybe there is a better one

**Comment by MalloZup** [comment]
fixed , feel free to share your pov

**Comment by meaksh** [comment]
@MalloZup that sounds good to me! :+1: :tada:
