### ISSUE TITLE
add archlinux and other cloud-os images

### ISSUE THREAD

**Issue by MalloZup** [MalloZup/ceph-open-terrarium#6]
add a module os image fro archlinux and/or other os images.

follow some structure as
https://github.com/MalloZup/ceph-open-terrarium/tree/master/terraform/libvirt/images/centos

**Comment by eric12345566** [comment]
Is ISO file ok?

**Comment by MalloZup** [comment]
hi @eric12345566 ! 

Iso would not fit. we nee qcow or raw

Take look here:  
https://github.com/dmacvicar/terraform-provider-libvirt

**Comment by MalloZup** [comment]
which distro would like to add? 

we need best official ones from mirrors

**Comment by MalloZup** [comment]
Done look at example
